version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: thinkspira-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: thinkspira
    volumes:
      - mongodb_data:/data/db
    networks:
      - thinkspira-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thinkspira-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/thinkspira?authSource=admin
      - SESSION_SECRET=your-super-secret-session-key-change-this-in-production
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:5000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - mongodb
    networks:
      - thinkspira-network

  # Frontend (for development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: thinkspira-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - thinkspira-network

volumes:
  mongodb_data:

networks:
  thinkspira-network:
    driver: bridge
